In [1]:
import torch
d5=[]
d6=[]
for i in range(5):
    d5.append(torch.load(f'../cache/llama/h2o_5_l3_i{i}.pth', map_location=torch.device('cpu')))
    d6.append(torch.load(f'../cache/llama/h2o_6_l3_i{i}.pth', map_location=torch.device('cpu')))

/tmp/ipykernel_442128/936581573.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  d5.append(torch.load(f'../cache/llama/h2o_5_l3_i{i}.pth', map_location=torch.device('cpu'

In [2]:
d5

[{'q': tensor([[[[ 1.1094, -0.1309,  0.5000,  ...,  3.8125,  0.8438, -3.3594]],
  
           [[-0.5391, -0.6836, -0.2754,  ..., -1.9375, -1.4141, -1.4844]],
  
           [[-1.8672,  0.5977,  0.4141,  ...,  6.5312, -0.0688, -0.0488]],
  
           ...,
  
           [[-0.7617,  0.5625,  0.2080,  ...,  6.1250, -0.6055,  0.5195]],
  
           [[ 1.0859, -0.8047,  0.5078,  ...,  0.4707, -0.7070,  0.5703]],
  
           [[-0.2441,  0.1279, -0.5391,  ...,  3.1406, -2.3281, -6.7812]]]],
         dtype=torch.bfloat16),
  'k': tensor([[[[-3.8818e-02, -3.5400e-02,  1.4038e-02,  ...,  4.9219e-01,
              5.3223e-02, -4.8633e-01],
            [-5.9326e-02, -4.0039e-02, -2.1057e-03,  ...,  4.4141e-01,
              5.1758e-02, -4.3555e-01],
            [-1.3916e-02,  6.7969e-01, -1.0234e+00,  ..., -3.8281e+00,
             -8.8867e-02,  4.0000e+00],
            ...,
            [ 1.0703e+00,  1.2109e+00,  1.4375e+00,  ..., -3.1719e+00,
              7.3438e-01,  3.3281e+00],
           

In [7]:
d5[0].keys()

dict_keys(['q', 'k', 'v', 'kv_seq_len', 'past_key_value', 'past_key_values_length', 'attention_mask', 'cache_kwargs', 'attn_weights', 'kv_hh', 'attn_output', 'hh_score'])

In [8]:
d5[0]['q']

tensor([[[[ 1.1094, -0.1309,  0.5000,  ...,  3.8125,  0.8438, -3.3594]],

         [[-0.5391, -0.6836, -0.2754,  ..., -1.9375, -1.4141, -1.4844]],

         [[-1.8672,  0.5977,  0.4141,  ...,  6.5312, -0.0688, -0.0488]],

         ...,

         [[-0.7617,  0.5625,  0.2080,  ...,  6.1250, -0.6055,  0.5195]],

         [[ 1.0859, -0.8047,  0.5078,  ...,  0.4707, -0.7070,  0.5703]],

         [[-0.2441,  0.1279, -0.5391,  ...,  3.1406, -2.3281, -6.7812]]]],
       dtype=torch.bfloat16)

In [9]:
def compare(d5_i, d6_i):
    keys = d5_i.keys()
    for k in keys:
        print('key ', k)
        print(d5_i[k] == d6_i[k])

In [10]:
for i in range(len(d5)):
    print('>> i', i)
    compare(d5[i], d6[i])

>> i 0
--------
key  q
tensor([[[[True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True]],

         ...,

         [[True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True]]]])
--------
key  k
tensor([[[[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., Tr

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [11]:
d5[4]

{'q': tensor([[[[ 0.3945,  0.8281,  0.6562,  ...,  3.8438, -0.9609, -3.3906]],
 
          [[ 0.1396, -0.6016, -0.2422,  ..., -1.8125, -1.4219, -1.1094]],
 
          [[-2.8750,  0.1016,  0.2324,  ...,  6.3750, -0.7891,  0.9688]],
 
          ...,
 
          [[-0.4727, -0.0547,  0.1934,  ...,  6.2500, -0.3555,  0.8008]],
 
          [[ 0.5820, -0.4043,  0.2715,  ...,  0.0591, -0.3457,  0.5117]],
 
          [[-0.1445,  0.2598,  0.2344,  ...,  2.3750, -5.3750, -6.0000]]]],
        dtype=torch.bfloat16),
 'k': tensor([[[[-3.8818e-02, -3.5400e-02,  1.4038e-02,  ...,  4.9219e-01,
             5.3223e-02, -4.8633e-01],
           [-5.9326e-02, -4.0039e-02, -2.1057e-03,  ...,  4.4141e-01,
             5.1758e-02, -4.3555e-01],
           [-1.3916e-02,  6.7969e-01, -1.0234e+00,  ..., -3.8281e+00,
            -8.8867e-02,  4.0000e+00],
           ...,
           [ 7.3047e-01,  9.1406e-01,  1.0156e+00,  ..., -3.0000e+00,
             6.5625e-01,  3.1719e+00],
           [ 3.3008e-01,  8.0078e-

In [13]:
d5[4].keys()

dict_keys(['q', 'k', 'v', 'kv_seq_len', 'past_key_value', 'past_key_values_length', 'attention_mask', 'cache_kwargs', 'attn_weights', 'kv_hh', 'attn_output', 'hh_score'])

In [15]:
torch.sum(d5[4]['q'] != d6[4]['q'])

tensor(0)

In [16]:
torch.sum(d5[4]['k'] != d6[4]['k'])


tensor(2098969)

In [17]:
torch.sum(d5[4]['v'] != d6[4]['v'])


tensor(2106113)

In [21]:
d5[4]['v'].shape

torch.Size([1, 32, 517, 128])

In [22]:
d6[4]['v'].shape

torch.Size([1, 32, 517, 128])

In [18]:
torch.sum(d5[3]['q'] != d6[3]['q'])

tensor(0)

In [20]:
torch.sum(d5[3]['v'] != d6[3]['v'])

tensor(0)

In [12]:
d6[4]

{'q': tensor([[[[ 0.3945,  0.8281,  0.6562,  ...,  3.8438, -0.9609, -3.3906]],
 
          [[ 0.1396, -0.6016, -0.2422,  ..., -1.8125, -1.4219, -1.1094]],
 
          [[-2.8750,  0.1016,  0.2324,  ...,  6.3750, -0.7891,  0.9688]],
 
          ...,
 
          [[-0.4727, -0.0547,  0.1934,  ...,  6.2500, -0.3555,  0.8008]],
 
          [[ 0.5820, -0.4043,  0.2715,  ...,  0.0591, -0.3457,  0.5117]],
 
          [[-0.1445,  0.2598,  0.2344,  ...,  2.3750, -5.3750, -6.0000]]]],
        dtype=torch.bfloat16),
 'k': tensor([[[[-3.8818e-02, -3.5400e-02,  1.4038e-02,  ...,  4.9219e-01,
             5.3223e-02, -4.8633e-01],
           [-5.9326e-02, -4.0039e-02, -2.1057e-03,  ...,  4.4141e-01,
             5.1758e-02, -4.3555e-01],
           [-2.5586e-01,  5.6641e-01, -6.9531e-01,  ..., -1.9453e+00,
            -1.0625e+00,  2.1875e+00],
           ...,
           [ 3.3008e-01,  8.0078e-01,  5.0781e-01,  ..., -3.3438e+00,
            -8.4375e-01,  3.4531e+00],
           [ 3.0859e-01,  1.4688e+

In [56]:
import torch
d5_rope=[]
d6_rope=[]
d5_pkv=[]
d6_pkv=[]
d5_repeat=[]
d6_repeat=[]
d5_kvhh=[]
d6_kvhh=[]
d5_pkw_update=[]
d6_pkw_update=[]
d5=[]
d6=[]
for i in range(5):
    d5_rope.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_rope.pth', map_location=torch.device('cpu')))
    d6_rope.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}_rope.pth', map_location=torch.device('cpu')))
    d5_pkv.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_pkv.pth', map_location=torch.device('cpu')))
    d6_pkv.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}_pkv.pth', map_location=torch.device('cpu')))
    d5_repeat.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_repeat.pth', map_location=torch.device('cpu')))
    d6_repeat.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}_repeat.pth', map_location=torch.device('cpu')))
    d5.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}.pth', map_location=torch.device('cpu')))
    d6.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}.pth', map_location=torch.device('cpu')))
    d5_kvhh.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_kvhh.pth', map_location=torch.device('cpu')))
    d6_kvhh.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}_kvhh.pth', map_location=torch.device('cpu')))
    d5_pkw_update.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_pkw_update.pth', map_location=torch.device('cpu')))
    d6_pkw_update.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}_pkw_update.pth', map_location=torch.device('cpu')))
    

/tmp/ipykernel_442128/3484282968.py:15: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  d5_rope.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_rope.pth', map_location=torch.

/tmp/ipykernel_442128/3484282968.py:23: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  d5_kvhh.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_kvhh.pth', map_location=torch.

In [58]:
torch.sum(d5_pkw_update[4]['k']!=d6_pkw_update[4]['k'])

tensor(0)

In [60]:
torch.sum(d5[4]['attention_mask']!=d6[4]['attention_mask'])

TypeError: sum(): argument 'input' (position 1) must be Tensor, not bool

In [61]:
d5[4]['attn_weights']

In [32]:
torch.sum(d5_pkv[4]['k']!=d6_pkv[4]['k'])

tensor(0)

In [33]:
torch.sum(d5_repeat[4]['k']!=d6_repeat[4]['k'])

tensor(0)

In [35]:
torch.sum(d5_repeat[4]['v']!=d6_repeat[4]['v'])

tensor(0)

In [34]:
torch.sum(d5[4]['k']!=d6[4]['k'])

tensor(2098969)

In [36]:
torch.sum(d5[4]['v']!=d6[4]['v'])

tensor(2106113)

In [40]:
torch.sum(d5[4]['kv_hh'][2]!=d6[4]['kv_hh'][2])

tensor(0)

In [41]:
d5[4]['kv_hh'][2]

tensor([[[[ 4.3869e-04,  1.5793e-03, -1.7853e-03,  ..., -7.7515e-03,
           -2.0313e-04,  9.9487e-03],
          [ 9.5367e-04,  6.4697e-03, -3.6011e-03,  ..., -6.9580e-03,
           -3.4943e-03,  6.3705e-04],
          [-2.1606e-02,  3.9258e-01,  2.6562e-01,  ...,  3.6328e-01,
            7.7148e-02, -6.0938e-01],
          ...,
          [-1.1279e-01, -4.7913e-03,  3.0664e-01,  ...,  2.2754e-01,
            3.8281e-01,  1.8555e-01],
          [-1.6797e-01, -1.7188e-01,  1.4160e-01,  ...,  2.8516e-01,
            2.3535e-01, -2.9297e-02],
          [-1.4062e-01, -8.0566e-03,  4.4141e-01,  ...,  1.6309e-01,
           -1.8848e-01,  1.3477e-01]],

         [[ 4.6387e-03,  6.8970e-03, -1.0498e-02,  ..., -3.8147e-03,
            2.8992e-03, -1.0986e-03],
          [ 9.3937e-05,  2.7008e-03, -1.1536e-02,  ...,  1.0132e-02,
            4.2319e-06,  2.3193e-03],
          [-4.0039e-02,  4.1016e-02, -1.6113e-01,  ...,  8.5938e-02,
            2.8125e-01,  1.2598e-01],
          ...,
     

In [44]:
print(d5[4]['k'])
print(d5[4]['k'].shape)

tensor([[[[-3.8818e-02, -3.5400e-02,  1.4038e-02,  ...,  4.9219e-01,
            5.3223e-02, -4.8633e-01],
          [-5.9326e-02, -4.0039e-02, -2.1057e-03,  ...,  4.4141e-01,
            5.1758e-02, -4.3555e-01],
          [-1.3916e-02,  6.7969e-01, -1.0234e+00,  ..., -3.8281e+00,
           -8.8867e-02,  4.0000e+00],
          ...,
          [ 7.3047e-01,  9.1406e-01,  1.0156e+00,  ..., -3.0000e+00,
            6.5625e-01,  3.1719e+00],
          [ 3.3008e-01,  8.0078e-01,  5.0781e-01,  ..., -3.3438e+00,
           -8.4375e-01,  3.4531e+00],
          [ 3.0859e-01,  1.4688e+00,  8.4375e-01,  ..., -3.3281e+00,
           -8.7891e-01,  3.4062e+00]],

         [[ 6.1951e-03,  2.2949e-02, -2.7588e-02,  ..., -4.2383e-01,
           -4.2969e-01, -3.4570e-01],
          [ 1.9531e-02, -5.6763e-03, -3.6133e-02,  ..., -3.8281e-01,
           -2.5586e-01, -1.9238e-01],
          [-8.0078e-02, -4.5312e-01, -2.4219e-01,  ...,  8.2812e-01,
            1.7734e+00,  1.3984e+00],
          ...,
     

In [46]:
print(d6[4]['k'])
print(d6[4]['k'].shape)

tensor([[[[-3.8818e-02, -3.5400e-02,  1.4038e-02,  ...,  4.9219e-01,
            5.3223e-02, -4.8633e-01],
          [-5.9326e-02, -4.0039e-02, -2.1057e-03,  ...,  4.4141e-01,
            5.1758e-02, -4.3555e-01],
          [-2.5586e-01,  5.6641e-01, -6.9531e-01,  ..., -1.9453e+00,
           -1.0625e+00,  2.1875e+00],
          ...,
          [ 3.3008e-01,  8.0078e-01,  5.0781e-01,  ..., -3.3438e+00,
           -8.4375e-01,  3.4531e+00],
          [ 3.0859e-01,  1.4688e+00,  8.4375e-01,  ..., -3.3281e+00,
           -8.7891e-01,  3.4062e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00]],

         [[ 6.1951e-03,  2.2949e-02, -2.7588e-02,  ..., -4.2383e-01,
           -4.2969e-01, -3.4570e-01],
          [ 1.9531e-02, -5.6763e-03, -3.6133e-02,  ..., -3.8281e-01,
           -2.5586e-01, -1.9238e-01],
          [ 3.3203e-02, -3.5645e-02, -3.3203e-02,  ...,  5.7812e-01,
            7.8125e-01,  6.2500e-01],
          ...,
     

In [49]:
d5[4]['k'][:, :, 3,:]

tensor([[[-0.2559,  0.5664, -0.6953,  ..., -1.9453, -1.0625,  2.1875],
         [ 0.0332, -0.0356, -0.0332,  ...,  0.5781,  0.7812,  0.6250],
         [-0.9492,  1.4141,  0.3398,  ..., -4.6562,  1.3906, -0.9570],
         ...,
         [ 0.4160, -0.1309,  0.3066,  ..., -2.3594, -1.4453,  0.3379],
         [ 0.0522, -0.8555,  0.4609,  ..., -1.5312, -1.4688, -1.6172],
         [-0.1709, -0.2949,  0.3887,  ..., -3.5469,  3.2031, -1.2734]]],
       dtype=torch.bfloat16)

In [50]:
d6[4]['k'][:, :, 2,:]

tensor([[[-0.2559,  0.5664, -0.6953,  ..., -1.9453, -1.0625,  2.1875],
         [ 0.0332, -0.0356, -0.0332,  ...,  0.5781,  0.7812,  0.6250],
         [-0.9492,  1.4141,  0.3398,  ..., -4.6562,  1.3906, -0.9570],
         ...,
         [ 0.4160, -0.1309,  0.3066,  ..., -2.3594, -1.4453,  0.3379],
         [ 0.0522, -0.8555,  0.4609,  ..., -1.5312, -1.4688, -1.6172],
         [-0.1709, -0.2949,  0.3887,  ..., -3.5469,  3.2031, -1.2734]]],
       dtype=torch.bfloat16)

In [51]:
import torch
d5_kvhh=[]
d6_kvhh=[]
d5_pkw_update=[]
d6_pkw_update=[]

for i in range(5):
    d5_kvhh.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_kvhh.pth', map_location=torch.device('cpu')))
    d6_kvhh.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}_kvhh.pth', map_location=torch.device('cpu')))
    d5_pkw_update.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_pkw_update.pth', map_location=torch.device('cpu')))
    d6_pkw_update.append(torch.load(f'../cache/llama/h2o_6/l3_i{i}_pkw_update.pth', map_location=torch.device('cpu')))
    

/tmp/ipykernel_442128/73442226.py:8: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  d5_kvhh.append(torch.load(f'../cache/llama/h2o_5/l3_i{i}_kvhh.pth', map_location=torch.dev

In [53]:
torch.sum(d5_kvhh[4]['k']!=d6_kvhh[4]['k'])

tensor(0)

In [54]:
torch.sum(d5_pkw_update[4]['k']!=d6_pkw_update[4]['k'])

tensor(2098969)

In [62]:
d5_final = torch.load(f'../cache/llama/h2o_5/l3_final.pth', map_location=torch.device('cpu'))
d6_final = torch.load(f'../cache/llama/h2o_6/l3_final.pth', map_location=torch.device('cpu'))

/tmp/ipykernel_442128/1437630781.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  d5_final = torch.load(f'../cache/llama/h2o_5/l3_final.pth', map_location=torch.device('c

In [66]:
torch.sum(d5_final['attn_output']!=d6_final['attn_output'])


tensor(0)

In [75]:
len(d5_final['past_key_value'][3])

2

In [77]:
torch.sum(d5_final['past_key_value'][3][0]!=d6_final['past_key_value'].key_cache[3][:, :, :516, :])

tensor(0)

In [67]:
torch.sum(d5_final['past_key_value']!=d6_final['past_key_value'])

TypeError: sum(): argument 'input' (position 1) must be Tensor, not bool

In [79]:
d5_final={}
d6_final={}

for i in range(3, 32):
    d5_final[i] = torch.load(f'../cache/llama/h2o_5/l{i}_final.pth', map_location=torch.device('cpu'))
    d6_final[i] = torch.load(f'../cache/llama/h2o_6/l{i}_final.pth', map_location=torch.device('cpu'))

/tmp/ipykernel_442128/1783226647.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  d5_final[i] = torch.load(f'../cache/llama/h2o_5/l{i}_final.pth', map_location=torch.devi

In [82]:
for i in range(3, 32):
    print(f'>> {i}')
    print(torch.sum(d5_final[i]['attn_output']!=d6_final[i]['attn_output']))

>> 3
tensor(0)
>> 4
tensor(0)
>> 5
tensor(0)
>> 6
tensor(0)
>> 7
tensor(0)
>> 8
tensor(0)
>> 9
tensor(0)
>> 10
tensor(0)
>> 11
tensor(0)
>> 12
tensor(0)
>> 13
tensor(0)
>> 14
tensor(0)
>> 15
tensor(0)
>> 16
tensor(0)
>> 17
tensor(0)
>> 18
tensor(0)
>> 19
tensor(0)
>> 20
tensor(0)
>> 21
tensor(0)
>> 22
tensor(0)
>> 23
tensor(0)
>> 24
tensor(0)
>> 25
tensor(0)
>> 26
tensor(0)
>> 27
tensor(0)
>> 28
tensor(0)
>> 29
tensor(0)
>> 30
tensor(0)
>> 31
tensor(0)


In [87]:
d5[0]['cache_kwargs']['cos'].shape

torch.Size([1, 1024, 128])

In [88]:
d5[0]['cache_kwargs']['cache_position']

tensor([   0,    1,    2,  ..., 1021, 1022, 1023])