In [125]:
import torch

# Assuming these variables are defined: N_H, TDST_BQ, MASK_K_BK
# Example values for demonstration (You should replace them with your actual values)
N_H = 40  # Example: Number of heads
TDST_BQ = 128  # Example: TDST divided by block size for query
MASK_K_BK = 256  # Example: MASK_K divided by block size for keys

# Initialize the tensors with example shapes
# Replace these with your actual tensors
indices = torch.zeros(N_H, TDST_BQ, MASK_K_BK, dtype=torch.long)
ks = torch.randint(low=0, high=MASK_K_BK, size=(N_H, TDST_BQ), dtype=torch.long)  # Random values as an example


In [126]:
range_tensor = torch.arange(MASK_K_BK, device=indices.device).expand_as(indices)

In [127]:
print(range_tensor)


tensor([[[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         ...,
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]],

        [[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         ...,
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]],

        [[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         ...,
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]],

        ...,

        [[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]

In [128]:
print(indices.shape)
print(ks)

torch.Size([40, 128, 256])
tensor([[ 80, 236, 111,  ..., 242, 252, 193],
        [239, 201, 216,  ..., 190, 178,  77],
        [155, 173,  67,  ..., 161, 137,  26],
        ...,
        [  3, 248,  10,  ..., 107,  73, 180],
        [ 64,   3, 223,  ..., 181,  30, 131],
        [  2,  79,  38,  ...,  87, 118,  95]])


In [129]:
mask = range_tensor >= ks.unsqueeze(-1)
print(ks.unsqueeze(-1).shape)
print(ks.unsqueeze(-1))

print(mask)
print(mask.shape)

torch.Size([40, 128, 1])
tensor([[[ 80],
         [236],
         [111],
         ...,
         [242],
         [252],
         [193]],

        [[239],
         [201],
         [216],
         ...,
         [190],
         [178],
         [ 77]],

        [[155],
         [173],
         [ 67],
         ...,
         [161],
         [137],
         [ 26]],

        ...,

        [[  3],
         [248],
         [ 10],
         ...,
         [107],
         [ 73],
         [180]],

        [[ 64],
         [  3],
         [223],
         ...,
         [181],
         [ 30],
         [131]],

        [[  2],
         [ 79],
         [ 38],
         ...,
         [ 87],
         [118],
         [ 95]]])
tensor([[[False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         ...,
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  T

In [130]:
indices

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [131]:
indices[mask] = 32000
print(indices)

tensor([[[    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         ...,
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000]],

        [[    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         ...,
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000]],

        [[    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         ...,
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [

In [132]:
import torch

# Assuming ks is your tensor with shape (N_H, TDST_BQ)
# Example tensor for demonstration purposes (replace with your tensor)
N_H = 2
TDST_BQ = 5
ks = torch.randint(low=0, high=20, size=(N_H, TDST_BQ))
print(ks)
# To find the maximum value across the entire tensor
max_value = ks.max().item()

print(f"The maximum value in ks is: {max_value}")

tensor([[15,  2,  5,  1, 18],
        [ 5, 17,  3, 15, 10]])
The maximum value in ks is: 18


In [133]:
import torch

ensemble_attn_mask_per_layer = torch.empty(3,4, 5, 0)
print(ensemble_attn_mask_per_layer.shape)
print(ensemble_attn_mask_per_layer)

indices = torch.ones(3,4,5)
print(indices.shape)
print(indices.unsqueeze(-1).shape)
ensemble_attn_mask_per_layer = torch.cat((ensemble_attn_mask_per_layer, indices.unsqueeze(-1)), dim=-1)
print(ensemble_attn_mask_per_layer.shape)
print(ensemble_attn_mask_per_layer)


torch.Size([3, 4, 5, 0])
tensor([], size=(3, 4, 5, 0))
torch.Size([3, 4, 5])
torch.Size([3, 4, 5, 1])
torch.Size([3, 4, 5, 1])
tensor([[[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
 

In [134]:
TSRC = 5
origin_sparsity = (torch.sum(ensemble_attn_mask_per_layer < TSRC)//5).item()

origin_sparsity

12

In [135]:
(ensemble_attn_mask_per_layer < TSRC).shape

torch.Size([3, 4, 5, 1])

In [136]:
ensemble_attn_mask_per_layer = torch.cat(ensemble_attn_mask_per_layer, dim=-1)


TypeError: cat() received an invalid combination of arguments - got (Tensor, dim=int), but expected one of:
 * (tuple of Tensors tensors, int dim, *, Tensor out)
 * (tuple of Tensors tensors, name dim, *, Tensor out)


In [ ]:
import torch

# Define an example tensor with the initial shape
N_H = 4
TDST = 1024
BLOCK_SIZE_Q = 64
MASK_K_BK = 2
ensemble_model_n = 3

# Create a tensor with the specified initial shape
tensor = torch.rand((N_H, TDST // BLOCK_SIZE_Q, MASK_K_BK, ensemble_model_n))

# Calculate new shape
new_first_dimension = N_H * (TDST // BLOCK_SIZE_Q)
new_last_dimension = MASK_K_BK * ensemble_model_n

# Reshape the tensor
reshaped_tensor = tensor.view(new_first_dimension, new_last_dimension)

print("Original shape:", tensor.shape)  # Output: (4, 16, 2, 3)
print("Reshaped shape:", reshaped_tensor.shape)  # Output: (64, 6)

Original shape: torch.Size([4, 16, 2, 3])
Reshaped shape: torch.Size([64, 6])


In [ ]:
print(reshaped_tensor)

tensor([[0.0543, 0.1904, 0.1274, 0.3107, 0.0958, 0.2595],
        [0.9638, 0.9202, 0.9052, 0.8515, 0.7359, 0.6152],
        [0.2663, 0.6266, 0.4071, 0.0938, 0.9798, 0.4514],
        [0.7393, 0.1167, 0.9352, 0.2723, 0.1543, 0.0890],
        [0.8946, 0.4289, 0.9273, 0.8273, 0.9801, 0.3374],
        [0.9915, 0.9311, 0.9238, 0.2278, 0.5803, 0.4495],
        [0.4288, 0.0264, 0.8844, 0.0894, 0.1071, 0.3184],
        [0.1842, 0.9013, 0.9048, 0.2102, 0.5804, 0.6663],
        [0.0732, 0.4532, 0.6602, 0.6666, 0.4118, 0.5718],
        [0.5520, 0.8793, 0.8612, 0.6264, 0.4713, 0.8292],
        [0.0932, 0.3912, 0.9973, 0.4357, 0.9339, 0.3855],
        [0.0038, 0.6807, 0.6606, 0.1933, 0.2436, 0.8034],
        [0.4190, 0.4909, 0.8589, 0.0355, 0.7662, 0.0952],
        [0.9935, 0.0621, 0.4886, 0.6496, 0.9542, 0.8495],
        [0.4079, 0.1637, 0.0294, 0.7211, 0.7922, 0.2984],
        [0.1756, 0.4312, 0.1844, 0.3051, 0.3343, 0.8732],
        [0.9312, 0.0740, 0.8891, 0.6068, 0.2214, 0.7877],
        [0.881

In [ ]:
for r in reshaped_tensor:
    unique_ensemble, counts = torch.unique(r, sorted=True, return_counts=True)
    print(unique_ensemble)
    print(counts)
    print("###")

tensor([0.0543, 0.0958, 0.1274, 0.1904, 0.2595, 0.3107])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.6152, 0.7359, 0.8515, 0.9052, 0.9202, 0.9638])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.0938, 0.2663, 0.4071, 0.4514, 0.6266, 0.9798])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.0890, 0.1167, 0.1543, 0.2723, 0.7393, 0.9352])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.3374, 0.4289, 0.8273, 0.8946, 0.9273, 0.9801])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.2278, 0.4495, 0.5803, 0.9238, 0.9311, 0.9915])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.0264, 0.0894, 0.1071, 0.3184, 0.4288, 0.8844])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.1842, 0.2102, 0.5804, 0.6663, 0.9013, 0.9048])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.0732, 0.4118, 0.4532, 0.5718, 0.6602, 0.6666])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.4713, 0.5520, 0.6264, 0.8292, 0.8612, 0.8793])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.0932, 0.3855, 0.3912, 0.4357, 0.9339, 0.9973])
tensor([1, 1, 1, 1, 1, 1])
###
tensor([0.0038, 0.1933, 0.2436, 

In [ ]:
t = torch.tensor([[1,3,4,3,2,2,3,1,0,0,0,5], [3,3,2,4,5,4,3,2,1,3,4,5]])

e, s = torch.unique(t, sorted=True, return_counts=True)
print(e)
print(s)

sorted_indices = torch.argsort(s, descending=True)
sorted_unique_values = e[sorted_indices]
sorted_counts = s[sorted_indices]
print(sorted_indices)
print(sorted_unique_values)
print(sorted_counts)

tensor([0, 1, 2, 3, 4, 5])
tensor([3, 3, 4, 7, 4, 3])
tensor([3, 2, 4, 0, 1, 5])
tensor([3, 2, 4, 0, 1, 5])
tensor([7, 4, 4, 3, 3, 3])


In [ ]:
import torch

# Example 2D tensor
tensor = torch.tensor([
    [1, 2, 2, 3],
    [4, 5, 4, 6],
    [7, 7, 8, 8]
])

# Reshape to flatten and retrieve unique values with indices
unique_elements, unique_indices = torch.unique(tensor, return_inverse=True)
print(unique_elements)
print(unique_indices)
# split_indices = torch.cumsum(torch.bincount(unique_indices[:-1]), dim=0)

# # Unique values per row
# unique_values_per_row = torch.split(unique_elements, split_indices.tolist())

# print("Unique values for each row:", unique_values_per_row)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 1, 2],
        [3, 4, 3, 5],
        [6, 6, 7, 7]])


In [ ]:
import torch

# Example 1: Two-dimensional tensors with unique elements and counts
# This could represent unique values and their counts from multiple runs or batches

# Two-dimensional tensor for unique elements
unique_ensemble = torch.tensor([
    [10, 20, 30, 40],  # First set of unique elements
    [15, 25, 35, 45]   # Second set of unique elements
])

# Two-dimensional tensor for corresponding counts
ensemble_cnt = torch.tensor([
    [5, 15, 10, 8],  # Corresponding counts for the first set
    [10, 20, 30, 40]  # Corresponding counts for the second set
])

print("Unique Ensemble (2D):")
print(unique_ensemble)

print("Ensemble Counts (2D):")
print(ensemble_cnt)

ensemble_method_final_inter_thresh = 15

# Create a boolean mask to filter elements based on the threshold
mask = ensemble_cnt >= ensemble_method_final_inter_thresh

# Apply the mask to `unique_ensemble` to get the filtered elements
filtered_unique_ensemble = unique_ensemble[mask]
print(mask)
print("Filtered unique ensemble:", filtered_unique_ensemble)

Unique Ensemble (2D):
tensor([[10, 20, 30, 40],
        [15, 25, 35, 45]])
Ensemble Counts (2D):
tensor([[ 5, 15, 10,  8],
        [10, 20, 30, 40]])
tensor([[False,  True, False, False],
        [False,  True,  True,  True]])
Filtered unique ensemble: tensor([20, 25, 35, 45])


In [ ]:
torch.empty(5,6)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 9.1835e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
t = torch.tensor([1,3,4,3,2,2,3,1,0,0,0,5])

print(t.shape)

torch.Size([12])


In [ ]:
import torch

# Original tensor
tensor = torch.tensor([
    [1, 2],
    [3, 4]
])

# Tensor to be added
new_elements = torch.tensor([
    [5, 6]
])

# Concatenate along rows (dim=0)
result = torch.cat((tensor, new_elements), dim=0)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# Original tensor
tensor = torch.tensor([
    [1, 2],
    [3, 4]
])

# Tensor to be added
new_elements = torch.tensor([
    [5, 6]
])

# Stack along a new axis
result = torch.stack((tensor, new_elements), dim=0)
print(result)

RuntimeError: stack expects each tensor to be equal size, but got [2, 2] at entry 0 and [1, 2] at entry 1

In [ ]:
# Two tensors with the same shape
tensor1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

tensor2 = torch.tensor([
    [7, 8, 9],
    [10, 11, 12]
])

# Stacking along a new dimension
result = torch.stack((tensor1, tensor2), dim=0)  # Works because shapes are identical
print(result)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [ ]:
tensor1 = torch.tensor(
    [1, 2, 3],)

tensor1[:2]

tensor([1, 2])

In [ ]:
test_tensor = torch.tensor([32000, 32000, 32000])

torch.all(test_tensor == 32000)

tensor(True)

In [ ]:
t = torch.load('../../cache/timber/qkv.pth')

In [ ]:
print(t['q'].shape)
print(t['k'].shape)
print(t['v'].shape)
print(t['mask_k'])
print(t['block_size_q'])
print(t['block_size_k'])

torch.Size([32, 4096, 128])
torch.Size([32, 4096, 128])
torch.Size([32, 4096, 128])
512
32
2


In [ ]:
x = tensor([[3, 3, 5, 5, 5],
        [3, 3, 2, 2, 3]])
unique_x, indices = torch.unique_consecutive(x, return_inverse=True)
indices -= indices.min(dim=1, keepdims=True)[0]
result = -torch.ones_like(x)
result = result.scatter_(1, indices, x)


TypeError: 'Tensor' object is not callable

In [ ]:
x = torch.tensor([[3, 3, 5, 5, 5],
            [3, 3, 2, 2, 3]])
unique_x, indices, cnt = torch.unique_consecutive(x, return_inverse=True, return_counts=True)


In [ ]:
unique_x

tensor([3, 5, 3, 2, 3])

In [ ]:
indices

tensor([[0, 0, 1, 1, 1],
        [2, 2, 3, 3, 4]])

In [ ]:
cnt

tensor([2, 3, 2, 2, 1])

In [ ]:
indices -= indices.min(dim=1, keepdims=True)[0]
result = -torch.ones_like(x)
result = result.scatter_(1, indices, x)

In [ ]:
x

tensor([[3, 3, 5, 5, 5],
        [3, 3, 2, 2, 3]])

In [ ]:
unique_x

tensor([3, 5, 3, 2, 3])

In [ ]:
indices

tensor([[0, 0, 1, 1, 1],
        [0, 0, 1, 1, 2]])

In [ ]:
result

tensor([[ 3,  5, -1, -1, -1],
        [ 3,  2,  3, -1, -1]])

In [354]:
x = torch.tensor([[1, 1, 5, 5, 5, 2],
            [3, 3, 2, 2, 2, 2]])
unique_x, indices, unique_cnt = torch.unique(x, return_inverse=True, sorted=True, return_counts=True)

In [355]:
unique_cnt

tensor([2, 5, 2, 3])

In [356]:
unique_x

tensor([1, 2, 3, 5])

In [357]:
indices

tensor([[0, 0, 3, 3, 3, 1],
        [2, 2, 1, 1, 1, 1]])

In [358]:
indices -= indices.min(dim=1, keepdims=True)[0]
print(indices)

tensor([[0, 0, 3, 3, 3, 1],
        [1, 1, 0, 0, 0, 0]])


In [359]:
cnt_x = (unique_x[None, None, :] == x[:, :, None]).long().sum(1)
cnt_x

tensor([[2, 1, 0, 3],
        [0, 4, 2, 0]])

In [360]:
indices

tensor([[0, 0, 3, 3, 3, 1],
        [1, 1, 0, 0, 0, 0]])

In [361]:
x

tensor([[1, 1, 5, 5, 5, 2],
        [3, 3, 2, 2, 2, 2]])

In [362]:
x.shape

torch.Size([2, 6])

In [363]:
torch.ones_like(x)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [364]:
# result = -torch.ones_like(x)
result = torch.full_like(x, 32000)
result = result.scatter_(1, indices, x)
result

tensor([[    1,     2, 32000,     5, 32000, 32000],
        [    2,     3, 32000, 32000, 32000, 32000]])

In [225]:
t = result[:, :, None] == unique_x[None, None, :]
t = t * torch.arange(len(unique_x))[None, None, :]
t = t.sum(-1)
result_cnt = torch.where(result > 0, cnt_x.gather(-1, t), -9999999)
result_cnt

tensor([[-9999999,        1, -9999999,        3, -9999999, -9999999],
        [       4,        2, -9999999, -9999999, -9999999, -9999999]])

In [224]:
result_cnt_sorted, indices = torch.sort(result_cnt, dim=-1, descending=True)
result_sorted = result.gather(-1, indices)
result_cnt_sorted, result_sorted

(tensor([[       3,        1, -9999999, -9999999, -9999999, -9999999],
         [       4,        2, -9999999, -9999999, -9999999, -9999999]]),
 tensor([[ 5,  2,  0, -1, -1, -1],
         [ 2,  3, -1, -1, -1, -1]]))

In [ ]:
cnt = -torch.ones(x)
cnt = cnt.scatter_(1, indices, x)

In [113]:
unique_x

tensor([2, 3, 5])

In [114]:
indices

tensor([[1, 1, 2, 2, 2, 0],
        [1, 1, 0, 0, 1, 1]])

In [115]:
result

tensor([[ 2,  3,  5, -1, -1, -1],
        [ 2,  3, -1, -1, -1, -1]])

In [116]:
unique_cnt
# cnt: [2, 3, 1], [2,2,2]

tensor([3, 6, 3])

In [187]:
x = torch.tensor([[0, 0, 5, 5, 5, 2],
            [3, 3, 2, 2, 0, 2]])

unique_x, indices, unique_cnt = torch.unique(x, return_inverse=True, sorted=False, return_counts=True)
indices -= indices.min(dim=1, keepdims=True)[0]
unique_x, indices, unique_cnt

(tensor([0, 2, 3, 5]),
 tensor([[0, 0, 3, 3, 3, 1],
         [2, 2, 1, 1, 0, 1]]),
 tensor([3, 4, 2, 3]))

In [188]:
unique_x[None, None, :]

tensor([[[0, 2, 3, 5]]])

In [189]:
x[:, :, None]

tensor([[[0],
         [0],
         [5],
         [5],
         [5],
         [2]],

        [[3],
         [3],
         [2],
         [2],
         [0],
         [2]]])

In [190]:
cnt_x = (unique_x[None, None, :] == x[:, :, None]).long().sum(1)
cnt_x

tensor([[2, 1, 0, 3],
        [1, 3, 2, 0]])

In [191]:
result = -torch.ones_like(x)
result = result.scatter_(1, indices, x)
result

tensor([[ 0,  2, -1,  5, -1, -1],
        [ 0,  2,  3, -1, -1, -1]])

In [193]:
t = result[:, :, None] == unique_x[None, None, :]
t = t * torch.arange(len(unique_x))[None, None, :]
t = t.sum(-1)
print(t)

tensor([[0, 1, 0, 3, 0, 0],
        [0, 1, 2, 0, 0, 0]])


In [ ]:
result_cnt = torch.where(result > 0, cnt_x.gather(-1, t), -9999999)
result_cnt_sorted, indices = torch.sort(result_cnt, dim=-1, descending=True)
result_sorted = result.gather(-1, indices)

In [194]:
result_cnt

tensor([[-9999999,        1, -9999999,        3, -9999999, -9999999],
        [-9999999,        3,        2, -9999999, -9999999, -9999999]])

In [195]:
result_sorted

tensor([[ 5,  2,  0, -1, -1, -1],
        [ 2,  3,  0, -1, -1, -1]])

In [179]:
result_cnt_sorted, result_sorted

(tensor([[       3,        1, -9999999, -9999999, -9999999, -9999999],
         [       3,        2, -9999999, -9999999, -9999999, -9999999]]),
 tensor([[ 5,  2,  0, -1, -1, -1],
         [ 2,  3,  0, -1, -1, -1]]))

In [264]:
x = torch.tensor([[0, 0, 5, 5, 5],
            [3, 3, 4, 4, 6]])
unique_x, indices = torch.unique_consecutive(x, return_inverse=True)
indices -= indices.min(dim=1, keepdims=True)[0]
result = -torch.ones_like(x)
result = result.scatter_(1, indices, x)
result

tensor([[ 3,  5, -1, -1, -1],
        [ 3,  2,  3, -1, -1]])

In [278]:
ensemble_attn_mask_per_layer = torch.tensor([[1, 1, 3, 3, 3, 5],
            [3, 3, 4, 4, 4, 4]])

unique_x, indices, unique_cnt = torch.unique_consecutive(ensemble_attn_mask_per_layer, return_inverse=True, return_counts=True)
indices -= indices.min(dim=1, keepdims=True)[0]


In [279]:
indices

tensor([[0, 0, 1, 1, 1, 2],
        [0, 0, 1, 1, 1, 1]])

In [367]:
ensemble_attn_mask_per_layer = torch.tensor([[1, 1, 3, 3, 3, 5,6,6,6,6,8,8,8,10,10,10,10,10,10, 11],
            [3, 3, 4, 4, 4, 4,5,5,5,5,5,5,6,6,7,7,7,9,9,9]])

unique_x, indices, unique_cnt = torch.unique(ensemble_attn_mask_per_layer, return_inverse=True, return_counts=True)
indices -= indices.min(dim=1, keepdims=True)[0]
cnt_x = (unique_x[None, None, :] == ensemble_attn_mask_per_layer[:, :, None]).long().sum(1)
result = -torch.ones_like(ensemble_attn_mask_per_layer)
# result = torch.full_like(ensemble_attn_mask_per_layer, 32000)
result = result.scatter_(1, indices, ensemble_attn_mask_per_layer)
t = result[:, :, None] == unique_x[None, None, :]
t = t * torch.arange(len(unique_x))[None, None, :]
t = t.sum(-1)
result_cnt = torch.where(result > 0, cnt_x.gather(-1, t), -9999999)
ensemble_cnt_sorted, indices = torch.sort(result_cnt, dim=-1, descending=True)
ensemble_sorted = result.gather(-1, indices)



In [368]:
ensemble_cnt_sorted, ensemble_sorted

(tensor([[       6,        4,        3,        3,        2,        1,        1,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999, -9999999,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999],
         [       6,        4,        3,        3,        2,        2, -9999999,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999, -9999999,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999]]),
 tensor([[10,  6,  3,  8,  1,  5, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
          -1, -1],
         [ 5,  4,  7,  9,  6,  3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
          -1, -1]]))

In [373]:
ensemble_attn_mask_per_layer = torch.tensor([[1, 1, 3, 3, 3, 5,6,6,6,6,8,8,8,10,10,10,10,10,10, 11],
            [3, 3, 4, 4, 4, 4,5,5,5,5,5,5,6,6,7,7,7,9,9,9]])

unique_x, indices, unique_cnt = torch.unique(ensemble_attn_mask_per_layer, return_inverse=True, return_counts=True)
indices -= indices.min(dim=1, keepdims=True)[0]
cnt_x = (unique_x[None, None, :] == ensemble_attn_mask_per_layer[:, :, None]).long().sum(1)
# result = -torch.ones_like(ensemble_attn_mask_per_layer)
result = torch.full_like(ensemble_attn_mask_per_layer, 32000)
result = result.scatter_(1, indices, ensemble_attn_mask_per_layer)
t = result[:, :, None] == unique_x[None, None, :]
t = t * torch.arange(len(unique_x))[None, None, :]
t = t.sum(-1)
result_cnt = torch.where(result < 32000, cnt_x.gather(-1, t), -9999999)
ensemble_cnt_sorted, indices = torch.sort(result_cnt, dim=-1, descending=True)
ensemble_sorted = result.gather(-1, indices)



In [374]:
ensemble_cnt_sorted, ensemble_sorted

(tensor([[       6,        4,        3,        3,        2,        1,        1,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999, -9999999,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999],
         [       6,        4,        3,        3,        2,        2, -9999999,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999, -9999999,
          -9999999, -9999999, -9999999, -9999999, -9999999, -9999999]]),
 tensor([[   10,     6,     3,     8,     1,     5,    11, 32000, 32000, 32000,
          32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000],
         [    5,     4,     7,     9,     6,     3, 32000, 32000, 32000, 32000,
          32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000, 32000]]))

: 

In [324]:
ensemble_method_final_inter_thresh = 2
mask =  ensemble_cnt_sorted>= ensemble_method_final_inter_thresh
print(mask)
mask.sum(-1)

tensor([[ True,  True,  True,  True,  True, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False]])


tensor([5, 6])

In [328]:
ensemble_sorted

tensor([[10,  6,  3,  8,  1,  5, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1],
        [ 5,  4,  7,  9,  6,  3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1]])

In [330]:
result = torch.where(mask, ensemble_sorted, torch.tensor(-1))
result

tensor([[10,  6,  3,  8,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1],
        [ 5,  4,  7,  9,  6,  3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1]])

In [332]:
ensemble_cnt_filtered = torch.where(mask, ensemble_cnt_sorted, torch.tensor(-1))
ensemble_cnt_filtered

tensor([[ 6,  4,  3,  3,  2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1],
        [ 6,  4,  3,  3,  2,  2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1]])

In [325]:
ensemble_sorted[mask]

TypeError: view() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (!Tensor!)
 * (tuple of ints size)
      didn't match because some of the arguments have invalid types: (!Tensor!)


In [327]:
ensemble_cnt_sorted[mask]

tensor([6, 4, 3, 3, 2, 6, 4, 3, 3, 2, 2])

In [333]:
import torch

# Given tensor
tensor = torch.tensor([
    [6, 4, 3, 3, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
    [6, 4, 3, 3, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
])

# Create a mask for positions with -1
is_negative_one = tensor == -1

# Get the first index where all rows contain -1
# Calculate the indices of the first -1 for each row
first_negative_one_indices = is_negative_one.int().argmax(dim=1)

# Find the minimum index across all rows where -1 starts
first_all_negative_one_index = first_negative_one_indices.min()

print("First index where all rows have -1:", first_all_negative_one_index.item())

First index where all rows have -1: 5


In [2]:
import torch

# Shape parameters
N = 4  # Batch size
T_DST = 128
mask_k = 256
block_size_q = 4
block_size_k = 8

# Create a sample tensor for indices with the given shape
indices = torch.arange(N * (T_DST // block_size_q) * (mask_k // block_size_k)).view(N, T_DST // block_size_q, mask_k // block_size_k)

# Create the ensemble_attn_mask_per_layer tensor with an initial shape (last dimension is 0)
ensemble_attn_mask_per_layer = torch.empty((N, T_DST // block_size_q, mask_k // block_size_k, 0))
print(ensemble_attn_mask_per_layer)
# Concatenate the indices tensor along the last dimension of ensemble_attn_mask_per_layer
ensemble_attn_mask_per_layer = torch.cat((ensemble_attn_mask_per_layer, indices.unsqueeze(-1)), dim=-1)

# Now the shape should be (N, T_DST // block_size_q, mask_k // block_size_k, 1)
print("Updated shape:", ensemble_attn_mask_per_layer.shape)
print(ensemble_attn_mask_per_layer)
print(indices)

tensor([], size=(4, 32, 32, 0))
Updated shape: torch.Size([4, 32, 32, 1])
tensor([[[[0.0000e+00],
          [1.0000e+00],
          [2.0000e+00],
          ...,
          [2.9000e+01],
          [3.0000e+01],
          [3.1000e+01]],

         [[3.2000e+01],
          [3.3000e+01],
          [3.4000e+01],
          ...,
          [6.1000e+01],
          [6.2000e+01],
          [6.3000e+01]],

         [[6.4000e+01],
          [6.5000e+01],
          [6.6000e+01],
          ...,
          [9.3000e+01],
          [9.4000e+01],
          [9.5000e+01]],

         ...,

         [[9.2800e+02],
          [9.2900e+02],
          [9.3000e+02],
          ...,
          [9.5700e+02],
          [9.5800e+02],
          [9.5900e+02]],

         [[9.6000e+02],
          [9.6100e+02],
          [9.6200e+02],
          ...,
          [9.8900e+02],
          [9.9000e+02],
          [9.9100e+02]],

         [[9.9200e+02],
          [9.9300e+02],
          [9.9400e+02],
          ...,
          [1.0210e+